import:
  - display/desktop/xsetroot
  - display/desktop/feh
  - display/color/zenburn
  - display/notice
  - display/client
  - display/tags
  - display/status/music/mpd
  - display/status/volume/amixer
  - display/status/storage/df
  - display/status/system/loadavg
  - display/status/time
  - control/mouse
  - control/keyboard/nate

prefer:
  terminal: urxvt
  browser: firefox
  editor: gvim
  filer: thunar

display:
  bar: bottom
  # font: -*-terminus-*-*-*-*-14-*-*-*-*-*-*-*
  # furxvt*ont:  xft:Bitstream Vera Sans Mono:autohinting=true:size=13
  font:      xft:Inconsolata:size=13
  border: 1
  column:
    mode: default
    rule: |
      /.*/ -> 53+47
  client:
    - /\b(xconsole|alsamixer|XMMS|Sonata)\b/  : 1
    - /^chrome:Chrome:Untitled/               : mail
    - /^chrome:Chrome:Chromium Options$/      : '~'
    - /^pidgin:|:WeeChat\b/                   : chat
